// Scans data/ and emits src/generated.ts with static imports of every
// content JSON file, so both Next.js and Metro can bundle content without
// runtime filesystem access.
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const dataDir = join(root, '..', 'data');
const outFile = join(root, '..', 'src', 'generated.ts');

function scan(kind) {
  const entries = [];
  const kindDir = join(dataDir, kind);
  for (const locale of readdirSync(kindDir).sort()) {
    for (const file of readdirSync(join(kindDir, locale)).sort()) {
      if (!file.endsWith('.json')) continue;
      const id = file.replace(/\.json$/, '');
      entries.push({ locale, id, path: `../data/${kind}/${locale}/${file}` });
    }
  }
  return entries;
}

const temples = scan('temples');
const circuits = scan('circuits');

let src = '// AUTO-GENERATED by scripts/generate.mjs — do not edit.\n';
src += "import type { Temple, Circuit } from '@temple/core';\n\n";

const varName = (kind, e, i) => `${kind}_${i}`;

temples.forEach((e, i) => {
  src += `import ${varName('t', e, i)} from '${e.path}';\n`;
});
circuits.forEach((e, i) => {
  src += `import ${varName('c', e, i)} from '${e.path}';\n`;
});

src += '\nexport const templeData = [\n';
temples.forEach((e, i) => {
  src += `  ${varName('t', e, i)} as unknown as Temple,\n`;
});
src += '];\n\nexport const circuitData = [\n';
circuits.forEach((e, i) => {
  src += `  ${varName('c', e, i)} as unknown as Circuit,\n`;
});
src += '];\n';

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, src);
console.log(
  `generated.ts: ${temples.length} temple files, ${circuits.length} circuit files`
);
